# Dockerfile.rocm
FROM stable-diffusion_rocm-base 

# For convenience
RUN mkdir -p /stablediff-web/models/Stable-diffusion 

# Grab ComfyUI source
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /comfyui_temp

WORKDIR /comfyui_temp

RUN pip install -r requirements.txt

WORKDIR /comfyui

