version: '3'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
  
  rocm-base:
    build:
      context: .
      dockerfile: Dockerfile
      target: rocm-base
    environment:
      TZ: "America/Phoenix"
      ROC_ENABLE_PRE_VEGA: 1
      ##############################
      # Set based on your hardware #
      ############################## 
      # ROCR_VISIBLE_DEVICES: 1
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      PYTORCH_HIP_ALLOC_CONF: "garbage_collection_threshold:0.9,max_split_size_mb:512"

  stablediff-rocm-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: stablediff-webui-runner
    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      COMMANDLINE_ARGS: "--listen --medvram --upcast-sampling --opt-sub-quad-attention --precision full --no-half --skip-torch-cuda-test"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "rocm-smi; . /stablediff.env; echo 'HSA_OVERRIDE_GFX_VERSION: ${HSA_OVERRIDE_GFX_VERSION}'; echo launch.py $COMMANDLINE_ARGS;
      if [ ! -d /stablediff-web/.git ]; then
        cp -a /sdtemp/. /stablediff-web/
      fi;
      python launch.py"
    ports:
      - "7860:7860"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mounts/cache:/root/.cache:Z
      - ./mounts/stablediff.env:/stablediff.env:Z
      - ./mounts/stablediff-web:/stablediff-web:Z
      - ./mounts/stablediff-models:/stablediff-web/models/Stable-diffusion:Z

  stablediff-comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      target: comfyui-runner
    entrypoint: ["/bin/sh", "-c"]
    environment:
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
    command: >
      "rocm-smi; 
      if [ ! -d /comfyui/.git ]; then
        cp -a /comfyui_temp/. /comfyui/
      fi;
      python main.py --listen"
    ports:
      - "7860:8188"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mounts/comfyui-web:/comfyui:Z
      - ./mounts/stablediff-web/models:/comfyui/models:Z
      - ./mounts/stablediff-models:/comfyui/models/checkpoints:Z
      - ./mounts/comfyui-output:/comfyui/output:Z

