version: '3'
services:

  rocm-base:
    build:
      context: .
      dockerfile: Dockerfile.rocm
    container_name: rocm-base
    environment:
      TZ: "America/Phoenix"
      ROC_ENABLE_PRE_VEGA: 1
      ## IMPORTANT!
      #ROCR_VISIBLE_DEVICES: 1
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      PYTORCH_HIP_ALLOC_CONF: "garbage_collection_threshold:0.9,expandable_segments:True,max_split_size_mb:128"

  stablediff-rocm-web:
    build: 
      context: .
      dockerfile: Dockerfile.sd
    depends_on: rocm-base
    container_name: stablediff-runner
    environment:
      COMMANDLINE_ARGS: "--listen --medvram --no-half --skip-torch-cuda-test"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "rocm-smi; . /stablediff.env; echo launch.py $$COMMANDLINE_ARGS;
      if [ ! -d /stablediff-web/.git ]; then
        cp -a /sdtemp/. /stablediff-web/
      fi;
      python launch.py"
    ports:
      - "7860:7860"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mounts/cache:/root/.cache
      - ./mounts/stablediff.env:/stablediff.env
      - ./mounts/stablediff-web:/stablediff-web
      - ./mounts/stablediff-models:/stablediff-web/models/Stable-diffusion

  stablediff-comfyui:
    build: 
      context: .
      dockerfile: Dockerfile.comfyui
    depends_on: rocm-base
    container_name: comfyui-runner
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "rocm-smi; ls -al; pwd;
      if [ ! -d /comfyui/.git ]; then
        cp -a /comfyui_temp/. /comfyui/
      fi;
      python main.py --listen"
    ports:
      - "7860:8188"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mounts/comfyui-web:/comfyui
      - ./mounts/stablediff-web/models:/comfyui/models
      - ./mounts/stablediff-models:/comfyui/models/checkpoints
      - ./mounts/comfyui-output:/comfyui/output

